server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

#mybatisPlus
mybatis-plus:
  mapper-locations: classpath:com/plus/mapper/*.xml
  type-aliases-package: com.plus.pojo

